[project]
name = "database"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Himansh Mudigonda", email = "himudigonda@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "sqlmodel>=0.0.22",
    "asyncpg>=0.29.0",
    "alembic>=1.13.1",
    "pydantic-settings>=2.2.1"
]

[build-system]
requires = ["uv_build>=0.9.27,<0.10.0"]
build-backend = "uv_build"
